---
# MongoDB Express Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongo-express-config
              key: ME_CONFIG_MONGODB_SERVER
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mongo-express-config
              key: ME_CONFIG_BASICAUTH_USERNAME
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-express-secret
              key: ME_CONFIG_BASICAUTH_PASSWORD
        - name: ME_CONFIG_MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: mongo-express-secret
              key: ME_CONFIG_MONGODB_URL
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-express-secret
              key: ME_CONFIG_MONGODB_ADMINUSERNAME
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-express-secret
              key: ME_CONFIG_MONGODB_ADMINPASSWORD
        - name: ME_CONFIG_SITE_BASEURL
          valueFrom:
            configMapKeyRef:
              name: mongo-express-config
              key: ME_CONFIG_SITE_BASEURL
        - name: ME_CONFIG_SITE_COOKIESECRET
          valueFrom:
            configMapKeyRef:
              name: mongo-express-config
              key: ME_CONFIG_SITE_COOKIESECRET
        - name: ME_CONFIG_SITE_SESSIONSECRET
          valueFrom:
            configMapKeyRef:
              name: mongo-express-config
              key: ME_CONFIG_SITE_SESSIONSECRET
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5

---
# MongoDB Express Service
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  labels:
    app: mongo-express
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP